CREATE TABLE [dbo].[Entrepeneaur]
(
	[UserEmail] VARCHAR(100) NOT NULL PRIMARY KEY,
	[Presentation] VARCHAR(220) NULL,
	CONSTRAINT [FK_Entrepeneaur_User] FOREIGN KEY ([UserEmail]) REFERENCES [User]([Email]) ON DELETE CASCADE ON UPDATE CASCADE
)
