CREATE TABLE [dbo].[Likes]
(
	[ClientEmail]   VARCHAR(100) NOT NULL PRIMARY KEY,
	[CategoryTitle]  VARCHAR(30) NOT NULL
	--CONSTRAINT FK_Category FOREIGN KEY (CategoryTitle) REFERENCES Category(Title) ON DELETE CASCADE ON UPDATE CASCADE
)
