CREATE TABLE [dbo].[Members]
(
	[UserEmail] VARCHAR(20) NOT NULL PRIMARY KEY,
	[Score] INT NULL,
	[Lat] FLOAT NULL,
	[Long] FLOAT NULL,
	CONSTRAINT [FK_User_Email] FOREIGN KEY ([UserEmail]) REFERENCES [USER]([Email]) ON DELETE CASCADE ON UPDATE CASCADE
)