CREATE TABLE [dbo].[Members]
(
	[User_Email] VARCHAR(100) NOT NULL PRIMARY KEY,
	[Score] INT NULL,
	[Lat] FLOAT NULL,
	[Long] FLOAT NULL,
	CONSTRAINT [FK_Members_User] FOREIGN KEY ([User_Email]) REFERENCES [User]([Email]) ON DELETE CASCADE ON UPDATE CASCADE
)